function [H] = Extract_FC(I,FG)
% Filter the image and return the fusion-code feature.
% Input:
%   I - Input grayscale image (128x128)
%   FG - Gabor filter bank generated by Generate_Gabor_FC()
% Output:
%   H - Fusion-code real and imaginary features (32x64 matrix)

M = cell(1,4);
P = cell(1,4);
for i = 1:4
    factor1 = conv2(I,FG{i},'same'); % Filter the image in four orientations
    factor2 = conj(factor1); % Complex conjugate of the filtered matrix
    
    IM = sqrt(factor1.*factor2); % Multiply the two complex matrices and take the square root
    Mj = IM(1:4:end,1:4:end); % Downsample the filtered magnitude image (32x32)
    M{i} = Mj; % Store the sampled magnitude image for each orientation
    
    f1 = sqrt(-1)*(factor2-factor1);
    f2 = factor1 + factor2;
    IP = atan2(f1,f2); % Four-quadrant arctangent
    Pj = IP(1:4:end,1:4:end); % Downsample the phase image (32x32)
    P{i} = Pj;  % Store the sampled phase image for each orientation
end

Orien = zeros(32,32); % Store the dominant orientation index for each pixel
for x = 1:32
    for y = 1:32
        temp = [M{1}(x,y),M{2}(x,y),M{3}(x,y),M{4}(x,y)]; % Temporary values for the four orientations
        [~,maxIndex] = max(temp); % Get the index of the maximum value
        Orien(x,y) = maxIndex; % Encode the pixel with an orientation index (1,2,3,4)
    end
end


FK = zeros(32,32);
for h = 1:32
    for w = 1:32
        k = Orien(h,w); % Get the selected orientation
        s = P{k}(h,w); % Get the phase value
        
        % Convert to the range (0, 2*pi) and obtain the final phase map
        if s<0
            FK(h,w) = s + 2*pi;
        else
            FK(h,w) = s;
        end
    end
end

Hr = zeros(32,32);
Hi = zeros(32,32);
for h = 1:32
    for w = 1:32
        if FK(h,w) >= 0 && FK(h,w) < (pi/2)
            Hr(h,w) = 1;
            Hi(h,w) = 1;
        elseif FK(h,w) >= (pi/2) && FK(h,w) < pi
            Hi(h,w) = 1;
        elseif FK(h,w) >= (3*pi/2) && FK(h,w) < (2*pi)
            Hr(h,w) = 1;
        end
    end
end
H = [Hr,Hi]; % Merge the real and imaginary features into one 32x64 feature matrix
end
