function [MTCC] = Extract_MTCC(I,CC_G)
% Filter the image and return the processed feature.
% Input:
%   I - Input grayscale image (128x128)
%   CC_G - Gabor filter bank generated by Generate_NpGabor_CC_BOCV_EBOCV()
% Output:
%   MTCC - Twelve directional binary feature matrices

MTCC = cell(1,12);  

for i = 1:6
    P = conv2(I,CC_G{i},'same'); % Filter the image in six orientations
    P2 = conv2(P,CC_G{i},'same');
    MTCC{i} = P(1:4:end,1:4:end)>0; % Store the first-stage binary map
    MTCC{i+6} = P2(1:4:end,1:4:end)>0; % Store the second-stage binary map
end
end
