function [OLOF] = Extract_OC(I,OC)
% Filter the image and return the processed feature.
% Input:
%   I - Input grayscale image (128x128)
%   OC - Gaussian filter bank generated by Generate_Gaussian_OC()
% Output:
%   OLOF - Filtered, downsampled, and binarized feature

OLOF = cell(1,3); % Temporary cell array for the three orientations
for i = 1:3
    P = conv2(I,OC{i},'same'); % Filter the image in three orientations
    PD = P(1:4:end,1:4:end)>0; % Downsample and binarize
    OLOF{i} = PD; % Store the binary image feature for each orientation
end
end
