function [CC] = Extract_CC(I,CC_G)
% Filter the image and return a competitive-coding feature.
% Input:
%   I - Input grayscale image (128x128)
%   CC_G - Gabor filter bank generated by Generate_NpGabor_CC_BOCV_EBOCV()
% Output:
%   CC - Competitive code storing orientation information (32x32 matrix)

PD = cell(1,6); 
for i = 1:6
    P = conv2(I,CC_G{i},'same'); % Filter using only the real part
    PD{i} = P(1:4:end,1:4:end);   
end

CC = zeros(32,32); % Store the competitive code in a 32x32 matrix
for x = 1:32
    for y = 1:32
        temp=[PD{1}(x,y),PD{2}(x,y),PD{3}(x,y),PD{4}(x,y),PD{5}(x,y),PD{6}(x,y)];
        [~,k] = min(temp); % Get the minimum value and its index
        CC(x,y) = k-1; % Encode the pixel starting from 0
    end
end
end
