function [BOCV_PM] = Extract_EBOCV(I,CC_G)
% Filter the image and return the processed feature.
% Input:
%   I - Input grayscale image (128x128)
%   CC_G - Gabor filter bank generated by Generate_NpGabor_CC_BOCV_EBOCV()
% Output:
%   BOCV_PM - Six directional binary feature matrices and fragile-bit masks

BOCV = cell(1,6);   % Store the filtered matrices for each orientation
PM = cell(1,6); % Store the fragile-bit mask for each orientation

for i = 1:6
    P = conv2(I,CC_G{i},'same'); % Convolve the image with six orientations

    BOCV{i} = P(1:4:end,1:4:end)>0; % Store the downsampled binary image in the cell
    
    P = abs(P);  % Take absolute values to find coefficients near zero
    
    S = sort(P(:)); % Sort matrix elements in ascending order
    
    threshold = S(floor(numel(P)*0.08)); % Use the top 8% threshold for near-zero values
    
    absDSamp = P(1:4:end,1:4:end); % Downsampled absolute-value feature matrix
    % Build the fragile mask
    fragile = ones(32); % Use 0/1 to mark whether a value is close to zero
    for x=1:32
        for y=1:32
            if(absDSamp(x,y) < threshold)
                fragile(x,y) = 0; % Mark near-zero pixels
            end
        end
    end
    PM{i} = fragile;
end
BOCV_PM = struct('BOCV',BOCV,'PM',PM);
end
