function [CC] = Extract_FastCC(I,CC_G)
% Filter the image and return a competitive-coding feature.
% Input:
%   I - Input grayscale image (128x128)
%   CC_G - Gabor filter bank generated by Generate_NpGabor_CC_BOCV_EBOCV()
% Output:
%   FastCC - Competitive code storing orientation information (32x32 matrix)

feat = conv2(I,CC_G{1},'same');
feat1 = feat(1:4:end,1:4:end);   
feat = conv2(I,CC_G{4},'same');
feat2 = feat(1:4:end,1:4:end);   

CC = feat1>feat2;
end
