function [DRCC] = Extract_DRCC(I,DRCC_G)
% Filter the image and return the DRCC feature.
% Input:
%   I - Input grayscale image (128x128)
%   DRCC_G - Gabor filter bank generated by Generate_GaussianGabor_DRCC();
%            the seventh element is the Gaussian prefilter.
% Output:
%   DRCC - struct with dominant and neighbor maps after joint DRCC coding

I = conv2(double(I), DRCC_G{7}, "same");
feature = cell(1,6);
for i = 1:6
    P = conv2(I, DRCC_G{i}, "same");
    feature{i} = P(1:4:end, 1:4:end);
end

DRCC = DRCC_encode_responses(feature);
end
