function [PalmCode] = Extract_PC(I,G)
% Apply the filter and return the real and imaginary binary features.
% Input:
%   I - Input grayscale image (128x128)
%   G - Gabor filter generated by Generate_Gabor_PC()
% Output:
%   PalmCode - Filtered, downsampled, and binarized feature (32x64)

P = conv2(I,G,'same'); % Filter the image

% Downsample and binarize the image
PD=P(1:4:end,1:4:end); % Downsample the image

RE=real(PD)>0; % Binarize the real part
IM=imag(PD)>0; % Binarize the imaginary part

PalmCode = [RE IM]; % Concatenate the real and imaginary parts
end
