function [BOCV] = Extract_BOCV(I,CC_G)
% Filter the image and return the processed feature.
% Input:
%   I - Input grayscale image (128x128)
%   CC_G - Gabor filter bank generated by Generate_NpGabor_CC_BOCV_EBOCV()
% Output:
%   BOCV - Six directional binary feature matrices

BOCV = cell(1,6);  

for i = 1:6
    P = conv2(I,CC_G{i},'same'); % Filter the image in six orientations
    
    BOCV{i} = P(1:4:end,1:4:end)>0; % Store the downsampled binary image
end
end
