function [CC] = Extract_RLOC(I,MF)
% Filter the image and return a competitive-coding feature.
% Input:
%   I - Input grayscale image (128x128)
%   MF - Radon filter bank generated by Generate_MFRAT_RLOC()
% Output:
%   CC - 32x32 feature matrix after filtering, downsampling, and coding

PD = cell(1,6); % Temporary cell array for the six orientations
for i = 1:6
    P = conv2(I,MF{i},'same'); % Filter the image in six orientations
    PD{i} = P(1:4:end,1:4:end); % Downsample the filtered image (32x32)
end

CC = zeros(32,32); % Store the competitive code in a 32x32 matrix
for x = 1:32
    for y = 1:32
        temp=[PD{1}(x,y),PD{2}(x,y),PD{3}(x,y),PD{4}(x,y),PD{5}(x,y),PD{6}(x,y)];
        [~,k] = min(temp); % Get the minimum value and its index
        CC(x,y) = k-1; % Encode the pixel
    end
end
end
