function [EDM] = Extract_EDM(I,CC_G)
% Filter the image and return the EDM feature.
% Input:
%   I - Input grayscale image (128x128)
%   CC_G - Gabor filter bank generated by Generate_NpGabor_CC_BOCV_EBOCV()
% Output:
%   EDM - Six directional binary feature matrices after joint downsampling

responses = cell(1, 6);
for i = 1:6
    responses{i} = conv2(I, CC_G{i}, "same");
end

EDM = EDM_joint_downsample(responses);
end
