function [DOC] = Extract_DOC(I,DOC_G)
% Extract the competitive code feature after filtering the image.
% Input:
%   I - Input grayscale image for feature extraction (128x128)
%   DOC_G - Gabor filter bank generated by Generate_RectifiedGabor_DOC()
% Output:
%   DOC - Competitive code, a 32x64 matrix. The left 32x32 block stores
%         the smallest-direction index for each pixel, and the right 32x32
%         block stores the second smallest-direction index.

feature=cell(1,6);

% Extract the real-valued Gabor response for each of the six directions.
for i = 1:6
    P = conv2(I,DOC_G{i},'same');
    feature{i}=P(1:4:end,1:4:end);
end

% After collecting the six responses, choose the directions corresponding
% to the smallest values and store the related information.
% Two matrices are used to hold the competitive code information.
% The first column stores the direction index (1 to 6), and the second
% column stores the response value.

DOC1=ones(32);
DOC2=ones(32);
% Assign values to the competitive code.
for x =1:32
    for y=1:32
        % Sort the six directional responses for each pixel and keep the
        % smallest value and its index.
        temp=[feature{1}(x,y),feature{2}(x,y),feature{3}(x,y),...
            feature{4}(x,y),feature{5}(x,y),feature{6}(x,y),];
        [~,minindex]=sort(temp); % Sort in ascending order
        DOC1(x,y)=minindex(1)-1;
        DOC2(x,y)=minindex(2)-1;
    end
end
DOC = [DOC1 DOC2];
end
